car:
  rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_wheel_joint
    pid: {p: 200.0, i: 5.0, d: 10.0}
  front_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_steering_joint
    pid: {p: 1000.0, i: 10.0, d: 50.0}